devgree/classroom/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<id>', home, name='classroom_home'),
    path('<id>/students/', students, name='classroom_students'),
    path('<id>/teachers/', teachers, name='classroom_teachers'),
    path('join/', join_classroom, name='classroom_join'),
    path('<id>/delete/', delete_message, name='classroom_message_delete'),
    path('<id>/pin/', pin_messages, name='classroom_message_pin'),
]

devgree/devgree/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls')),
    path('accounts/', include('accounts.urls')),
    path('staff/', include('staff.urls')),
    path('student/', include('student.urls')),
    path('classroom/', include('classroom.urls')),
    path('', include('user.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

devgree/student/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='student_home'),
    path('notice/', notice, name='student_notice'),
    path('notice/<int:id>/', notice_view, name='student_notice_view'),
]

devgree/user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('contact/', ContactUsCreateView.as_view(), name='contact'),
    path('noticeboard/', NoticeboardListView.as_view(), name='noticeboard'),
    path('noticeboard/<int:id>/', NoticeboardDetailView.as_view(), name='noticeboard_detail'),
    path('grievance/', grievance_status, name='grievance'),
    path('grievance/create', GrievanceCreateView.as_view(), name='grievance_create'),
]

devgree/administrator/models.py
from email.mime import image
from django.db import models
from accounts.models import User

# Create your models here.
class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField()
    description = models.CharField(max_length = 250, blank=True, null=True)
    
    def __str__(self):
        return self.name


class Course(models.Model):
    LEVELS = (
        ('UG', 'UG'),
        ('PG', 'PG'),
    )
    SEMESTERS = (
        (6, '6'),
        (8, '8'),
    )
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)
    department = models.ForeignKey(to=Department,on_delete=models.CASCADE)
    level = models.CharField(max_length=25, choices=LEVELS)
    semesters = models.SmallIntegerField(choices=SEMESTERS)
    
    def __str__(self):
        return self.name

class Student(models.Model):
    BLOOD_GROUPS = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    )
    SEMESTERS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
    )

    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='student_user')
    phone = models.CharField(max_length=15, blank=True, null=True)
    course = models.ForeignKey(to=Course,on_delete=models.CASCADE)
    address = models.CharField(max_length=250, blank=True, null=True)
    blood_group = models.CharField(max_length=10, choices=BLOOD_GROUPS, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    register_number = models.CharField(max_length=20, unique=True)
    roll_number = models.CharField(max_length=20, unique=True)
    semester = models.IntegerField(choices=SEMESTERS)
    image = models.ImageField(upload_to='student_images', blank=True, null=True)

class Staff(models.Model):
    BLOOD_GROUPS = (
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
        ('O+', 'O+'),
        ('O-', 'O-'),
    )
    SEMESTERS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
    )

    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='staff_user')
    phone = models.CharField(max_length=15, blank=True, null=True)
    teacher_id = models.CharField(max_length=20, unique=True)
    department = models.ForeignKey(to=Department,on_delete=models.CASCADE)
    address = models.CharField(max_length=250, blank=True, null=True)
    blood_group = models.CharField(max_length=10, choices=BLOOD_GROUPS, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
   

class Room(models.Model):
    FLOOR = (
        (1, '1'),
        (2, '2')
    )
    
    TYPE = (
        ('AC', 'AC'),
        ('NON AC', 'NON AC')
    )

    STATUS = (
        ('AVAILABLE', 'AVAILABLE'),
        ('UNAVAILABLE', 'UNAVAILABLE')
    )

    BLOCK = (
        ('AIDED', 'AIDED'),
        ('SELF', 'SELF')
    )

    id = models.AutoField(primary_key=True)
    room_name = models.CharField(max_length=30, blank=True, null=True, unique=True)
    room_no = models.CharField(max_length=15, blank=True, null=True, unique=True)
    capacity = models.CharField(max_length=15, unique=True)
    type = models.CharField(max_length=10, choices=TYPE, blank=True, null=True)
    status = models.CharField(max_length=25, choices=STATUS, blank=True, null=True)
    floor = models.IntegerField(blank=True, choices=FLOOR)
    block = models.CharField(max_length=10, choices=BLOCK, blank=True, null=True)
    image = models.ImageField(upload_to='room_images', blank=True, null=True)

    def __str__(self):
        return self.room_name

class Event(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    department = models.ForeignKey(to=Department,on_delete=models.CASCADE)
    description = models.CharField(max_length = 250, blank=True, null=True)
    
    def __str__(self):
        return self.name


class Booking(models.Model):
    id = models.AutoField(primary_key=True)
    room = models.ForeignKey(to=Room,on_delete=models.CASCADE)
    booked_on = models.DateField(blank=True, null=True)
    booked_from = models.DateField(blank=True, null=True)
    booked_to = models.DateField(blank=True, null=True)
    event = models.ForeignKey(to=Event,on_delete=models.CASCADE)
    remarks = models.CharField(max_length = 250, blank=True, null=True)

class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone = models.CharField(max_length=15, unique=True)
    message = models.CharField(max_length = 250)

class ClassRoom(models.Model):
    SEMESTERS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
    )

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)
    semester = models.IntegerField(choices=SEMESTERS)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='classroom_images', blank=True, null=True)

class ClassRoomTeachers(models.Model):
    id = models.AutoField(primary_key=True)
    classroom = models.ForeignKey(to=ClassRoom, on_delete=models.CASCADE)
    teacher = models.ForeignKey(to=User, limit_choices_to={'staff': True}, on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)

class ClassroomMessage(models.Model):
    id = models.BigAutoField(primary_key=True)
    classroom = models.ForeignKey(to=ClassRoom, on_delete=models.CASCADE)
    message = models.TextField(max_length=25000)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    is_pinned = models.BooleanField(default=False)
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)
    file = models.FileField(upload_to='classroom_files', blank=True, null=True)

class Noticeboard(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, unique=True)
    body = models.TextField()
    department = models.ForeignKey(to=Department,on_delete=models.CASCADE, blank=True, null=True)
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)

class Grievance(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Resolved', 'Resolved'),
        ('Rejected', 'Rejected')
    )
    CREATED_BY = (
        ('Student', 'Student'),
        ('Staff', 'Staff'),
        ('Parent', 'Parent')
    )
    id = models.AutoField(primary_key=True)
    department = models.ForeignKey(to=Department,on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=15)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    status = models.CharField(max_length=25, choices=STATUS, default='Pending')
    response = models.TextField(null=True, blank=True)
    created_by = models.CharField(max_length=25, choices=CREATED_BY, default='Student')
    created_on = models.DateField(auto_now_add=True)
    updated_on = models.DateField(auto_now=True)

devgree/classroom/models.py
from django.db import models

# Create your models here.

devgree/student/models.py
from django.db import models

# Create your models here.

devgree/classroom/views.py
from pyexpat.errors import messages
from django.http import HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from administrator.models import *
from administrator.forms import *
from django.contrib import messages

# Create your views here.

@login_required
def home(request, id):
    context = {
        'object_list': ClassroomMessage.objects.order_by('-created_on').filter(classroom_id=id)[:100],
        'classroom': get_object_or_404(ClassRoom, id=id),
    }
    if request.method == "GET":
        context['form'] = ClassroomMessageForm()
        return render(request, 'classroom/home.html', context)
    elif request.method == "POST":
        form = ClassroomMessageForm(request.POST, files=request.FILES)
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.classroom_id = id
            message.save()
            messages.success(request, 'Message sent successfully.')
            return redirect('classroom_home', id=id)
        else:
            context['form'] = form
            return render(request, 'classroom/home.html', context)

def delete_message(request, id):
    message = get_object_or_404(ClassroomMessage, id=id)
    if message.user == request.user or request.user.is_staff:
        message.delete()
        messages.success(request, 'Message deleted successfully.')
        return redirect('classroom_home', id=message.classroom_id)
    else:
        return HttpResponseForbidden()

def students(request, id):
    classroom = get_object_or_404(ClassRoom, id=id)
    context = {
        'object_list': Student.objects.select_related('user').filter(course_id=classroom.course_id, semester=classroom.semester),
        'classroom': classroom,
    }
    return render(request, 'classroom/students.html', context)

def teachers(request, id):
    classroom = get_object_or_404(ClassRoom, id=id)
    context = {
        'object_list': ClassRoomTeachers.objects.select_related('teacher').filter(classroom_id=id),
        'classroom': classroom,
    }
    return render(request, 'classroom/teachers.html', context)

@login_required
def pin_messages(request, id):
    if not request.user.staff:
        return HttpResponseForbidden()
    
    message = get_object_or_404(ClassroomMessage, id=id)
    if ClassRoomTeachers.objects.filter(teacher=request.user, classroom=message.classroom_id).first():
        if message.is_pinned:
            message.is_pinned = False
        else:
            message.is_pinned = True
        message.save()
        messages.success(request, 'Message pinned successfully.')
    else:
        messages.error(request, 'You are not authorized to pin this message.')
    return redirect('classroom_home', id=message.classroom_id)


@login_required
def join_classroom(request):
    context = {}
    student = Student.objects.filter(user=request.user).first()
    if student is None:
        return HttpResponseNotFound()

    classroom = ClassRoom.objects.filter(course_id = student.course_id, semester = student.semester).first()

    if classroom is None:
        context["message"] = "No classroom has been created."
        return render(request, 'join_classroom.html', context)
    
    return redirect('classroom_home', id=classroom.id)

devgree/student/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from administrator.models import *

# Create your views here.
def home(request):
    return render(request, 'student/home.html')

def notice(request):
    student = Student.objects.get(user=request.user)
    context={
        'object_list': Noticeboard.objects.filter(department_id=student.course.department_id)
    }
    return render(request, 'student/notice.html', context)

def notice_view(request, id):
    notice = Noticeboard.objects.get(id=id)
    context={
        'object': notice
    }
    return render(request, 'student/notice_view.html', context)

devgree/classroom/templates/classroom/home.html
{% extends 'master.html' %}
{% load static %}

{% block content %}
<div style="max-width: 90%;">
    <h1 class="text-center py-4 font-bold text-xl">Classroom</h1>
    {% include 'classroom/shared/navbar.html' %}
    <div class="rounded border background-gray-100 shadow p-4 mt-5">
        <form method="post" enctype="multipart/form-data">
            {{ form.message }}
            <div class="text-red-600">
                {{ form.message.errors.as_ul }}
            </div>
            <div class="mt-2">
                {{ form.file }}
            </div>
            <div class="flex mt-2">
                {% csrf_token %}
                <button type="submit" class="bg-indigo-600 p-2 rounded text-white ml-auto">
                    <ion-icon name="send-outline"></ion-icon>
                    Send Message
                </button>
            </div>
        </form>
    </div>
    
    {% if object_list %}
    {% for message in object_list %}
    <div class="border rounded shadow p-4 my-4">
        <div class="d-flex">
            <div class="ml-auto block">
                <div class="text-gray-600">
                    <span>
                        <ion-icon name="person-outline"></ion-icon>
                        {{ message.user.get_full_name }}
                    </span>
                    <span>
                        <ion-icon name="time-outline"></ion-icon>
                        {{ message.created_on }}
                    </span>
                    
                    {% if user.staff %}
                    <span class="ml-2">
                        {% if message.is_pinned %}
                        <a href="{% url 'classroom_message_pin' id=message.id %}" class="text-green-600">
                            <ion-icon name="bookmark-outline"></ion-icon>
                        </a>
                        {% else %}
                        <a href="{% url 'classroom_message_pin' id=message.id %}" class="text-indigo-600">
                            <ion-icon name="bookmark-outline"></ion-icon>
                        </a>
                        {% endif %}
                        <a href="{% url 'classroom_message_delete' id=message.id %}" class="text-red-600" onclick="return confirm('Do you want to delete this message?');">
                            <ion-icon name="trash"></ion-icon>
                        </a>
                    </span>
                    {% endif %}
                        
                </div>
            </div>
        </div>
        {% autoescape off %}
            <div class="border rounded p-4">
                {{ message.message }}
            </div>
        {% endautoescape %}
        
        {% if message.file %}
            <a href="{{ message.file.url }}" class="text-indigo-600" download>Download file</a>
        {% endif %}
            
    </div>
    {% endfor %}
        
        
    {% endif %}
        
</div>


<script src="{% static 'assets/js/ckeditor.js' %}"></script>
<script>
    document.querySelector('#id_message').removeAttribute('required');
    ClassicEditor
        .create(document.querySelector('#id_message'), {
            licenseKey: '',
        })
        .then(editor => {
            window.editor = editor;
        })
        .catch(error => {
            console.error('Oops, something went wrong!');
            console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
            console.warn('Build id: cplm8a4kitvx-o4bffjm7j3li');
            console.error(error);
        });
</script>
{% endblock content %}

devgree/classroom/templates/classroom/students.html
{% extends 'master.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1 class="text-center py-4 font-bold text-xl">Students</h1>
    {% include 'classroom/shared/navbar.html' %}
    
    {% for i in object_list %}
    <div class="flex rounded border background-gray-100 shadow p-4 mt-2">
        
        {% if i.image %}
        <img src="{{ i.image.url }}" class="rounded-full" alt="" height="25" width="25">
        {% else %}
        <img src="https://dummyimage.com/50x50.jpg?text={{ i.user.first_name.0 }}" class="rounded-full" height="25" width="25" alt="">
        {% endif %}
            
        <span class="ml-4">{{ i.user.get_full_name }}</span>
    </div>
    {% endfor %}
        
</div>
{% endblock content %}

devgree/classroom/templates/classroom/teachers.html
{% extends 'master.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1 class="text-center py-4 font-bold text-xl">Teachers</h1>
    {% include 'classroom/shared/navbar.html' %}
    
    {% for i in object_list %}
    <div class="flex rounded border background-gray-100 shadow p-4 mt-2">
        
        {% if i.image %}
        <img src="{{ i.image.url }}" class="rounded-full" alt="" height="25" width="25">
        {% else %}
        <img src="https://dummyimage.com/50x50.jpg?text={{ i.teacher.first_name.0 }}" class="rounded-full" height="25" width="25" alt="">
        {% endif %}
            
        <span class="ml-4">{{ i.teacher.get_full_name }}</span>
    </div>
    {% endfor %}
        
</div>
{% endblock content %}